### ISSUE TITLE
Example app is not working properly

### ISSUE THREAD

**Issue by Noyal** [bkonyi/Flutter-Location-Plugin-Background#2]
I was able to build and debug the app, but when i click the register or unregister. I m getting an error
>E/GeofencingPlugin(21635): Failed to add geofence: com.google.android.gms.common.api.ApiException: 1000:

Is there any config I should do.

**Comment by bkonyi** [comment]
I think you meant to post this in [bkonyi/FlutterGeofencing](https://github.com/bkonyi/FlutterGeofencing).
